cmake_minimum_required(VERSION 3.16)
project(LIOM2022 LANGUAGES CXX)
find_package(casadi CONFIG REQUIRED)
add_executable(liom src/main.cpp src/corridor.cpp src/optimizer.cpp)
target_include_directories(liom PRIVATE include)
target_compile_features(liom PRIVATE cxx_std_17)
set_target_properties(liom PROPERTIES CXX_STANDARD 17 CXX_STANDARD_REQUIRED YES CXX_EXTENSIONS NO)
target_link_libraries(liom PRIVATE casadi::casadi)
if(MINGW)
  target_link_options(liom PRIVATE -static-libgcc -static-libstdc++ -municode)
endif()
